name: Build & Release Fake Utils

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6

      - name: Build executables
        run: |
          cd "4 - Logiciels Divers/fake-utils"
          pyinstaller --onefile --noconsole --hidden-import=PyQt6 fake-antivirus.py
          pyinstaller --onefile --noconsole --hidden-import=PyQt6 fake-cleaner.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: 4 - Logiciels Divers/fake-utils/dist/*

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./artifacts

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
