name: Build & Release Fake Utils

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executables
        run: |
          cd "4 - Logiciels Divers/fake-utils"
          pyinstaller --onefile --noconsole fake-antivirus.py
          pyinstaller --onefile --noconsole fake-cleaner.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            "4 - Logiciels Divers/fake-utils/dist/fake-antivirus"
            "4 - Logiciels Divers/fake-utils/dist/fake-cleaner"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Binaries Linux générés avec PyInstaller"
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fake-antivirus
          asset_name: fake-antivirus
          asset_content_type: application/octet-stream

      - name: Upload second binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fake-cleaner
          asset_name: fake-cleaner
          asset_content_type: application/octet-stream
